name = "piyolog-dashboard"
# SPA mode - serving static assets from dist/ with client-side routing
main = "workers-site/index.js"
compatibility_date = "2024-01-01"

# Static assets configuration
[site]
bucket = "./dist"

# Environment variables (secrets should be set via wrangler secret put)
[vars]
ENVIRONMENT = "production"