name = "piyolog-dashboard"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "piyolog-dashboard-db"
database_id = "" # Will be filled after creating the database

# Static assets configuration
[site]
bucket = "./dist"

# Environment variables (secrets should be set via wrangler secret put)
[vars]
ENVIRONMENT = "development"